name: Build and Release Go Application

on:
  push:
    tags:
      - 'v*'  # Запускать при пуше тега, начинающегося с "v"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Checkout репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Установить Go
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'  # Задайте нужную версию Go

      # Шаг 3: Сборка Go проекта
      - name: Build the Go project
        run: |
          go mod tidy
          GOOS=linux GOARCH=amd64 go build -o tblocker-linux-amd64 ./main.go

      # Шаг 4: Создание релиза на GitHub
      - name: Create GitHub release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: myapp-linux-amd64  # Укажите путь к собранному файлу

      # Шаг 5: Опубликовать релиз
      - name: Publish Release
        run: |
          echo "Release created and uploaded successfully."
